controllers/ArticleController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Article;
use app\models\ArticleSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use app\models\SearchForm;
use yii\helpers\Html;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    public function beforeAction($param) {
        $sear = new SearchForm();
        if ($sear->load(\Yii::$app->request->post())) {
            $q = Html::encode($sear->q);
            if ($q == NULL) {
               return TRUE; 
            }
            return $this->redirect(\Yii::$app->urlManager->createUrl(['site/search', 'q' => $q]));
        }
        return TRUE;
    }

    public function actionView($id)
    {
        $model = $this->findModel($id);
        $count = $model->count + 1;
        $model->count = $count;
        $model->save();
        return $this->render('view', [
            'model' => $model,
        ]);
    }

   
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/CartController.php
<?php

namespace app\controllers;

use app\models\Tovar;
use app\models\Cart;
use Yii;

class CartController extends \yii\web\Controller {

    public function actionAdd($id) {
        $this->layout = FALSE;
        $tovar = Tovar::findOne($id);
        if (empty($tovar)) {
            return false;
        }


        return $this->render('add', [
            'id' => $id,
            'tovar' => $tovar,
        ]);
    }
    
    public function actionAddnumb() {
        $id = Yii::$app->request->get('id');
        $numb = Yii::$app->request->get('numb');
        $this->layout = FALSE;
        $tovar = Tovar::findOne($id);
        if (empty($tovar)) {
            return false;
        }


        return $this->render('addnumb', [
            'id' => $id,
            'tovar' => $tovar,
            'numb' => $numb,
        ]);
    }

    public function actionView() {
        return $this->render('view');
    }
    
    public function actionNumb() {
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('numb', compact('session'));
    }
    public function actionShow() {
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('show', compact('session'));
    }
    
    
    public function actionClear() {
        return $this->render('clear');
    }
    
    public function actionDelitem($id) {
        return $this->render('delitem', [
            'id' => $id,
        ]);
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\Response;
use yii\data\Pagination;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SearchForm;
use app\models\Article;
use app\models\Tovar;

class SiteController extends Controller {

    public function beforeAction($param) {
        $sear = new SearchForm();
        if ($sear->load(\Yii::$app->request->post())) {
            $q = Html::encode($sear->q);
            if ($q == NULL) {
               return TRUE; 
            }
            return $this->redirect(\Yii::$app->urlManager->createUrl(['site/search', 'q' => $q]));
        }
        return TRUE;
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex() {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
                    'model' => $model,
        ]);
    }

    public function actionSearch() {
        $q = Yii::$app->getRequest()->getQueryParam('q');

        $query = Article::find()->orWhere(['like', 'name', $q])->orWhere(['like', 'body', $q]);
        $queryTovar = Tovar::find()->orWhere(['like', 'name', $q])->orWhere(['like', 'description', $q]);
        if ($query->count() > $queryTovar->count()) {
            $count = clone $query;
        } else {
            $count = clone $queryTovar;
        }

        $pages = new Pagination(['totalCount' => $count->count()]);
        $models = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();
        $modelTovar = $queryTovar->offset($pages->offset)
                ->limit($pages->limit)
                ->all();


        return $this->render('search', [
                'q' => $q,
                'models' => $models,
                'modelTovar' => $modelTovar,
                'pages' => $pages,
        ]);
    }

}

controllers/TovarController.php
<?php

namespace app\controllers;
use yii\data\Pagination;

use app\models\Tovar;
use app\models\SearchForm;
use yii\helpers\Html;

class TovarController extends \yii\web\Controller {
    
    public function beforeAction($param) {
        $sear = new SearchForm();
        if ($sear->load(\Yii::$app->request->post())) {
            $q = Html::encode($sear->q);
            if ($q == NULL) {
               return TRUE; 
            }
            return $this->redirect(\Yii::$app->urlManager->createUrl(['site/search', 'q' => $q]));
        }
        return TRUE;
    }

    public function actionViews($id) {
        
        $model = $this->findModel($id);
        $model->count ++;
        $model->save();
        return $this->render('views', [
                    'model' => $model,
        ]);
    }

    public function actionIndex() {
        $query = Tovar::find()->orderBy(['date_create' => SORT_ASC]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);
        $models = $query->offset($pages->offset)
                ->limit($pages->limit)
                ->all();

        return $this->render('index', [
               'models' => $models,
               'pages' => $pages,
        ]);
    }

    protected function findModel($id) {
        if (($model = Tovar::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;

$this->title = 'Цветы, подарки в Усть-Ордынском Флора+';
$tovars = \app\models\Tovar::find()->orderBy(['date_create'=> SORT_ASC])->where(['frontpage'=>1])->limit(8)->all();

/* $this->registerJsFile(
    '/web/js/shopcard.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);*/

use app\models\Setting;

$setting = Setting::find()->one();

?>
<div class="header-wrap">
    <div class="container">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 text-white">
            <?= $setting->text_header ?>
        </div>
    </div>
</div>
<div class="container">
    <h1 class="text-center mb-30">Продукция</h1>
    <div class="row">
        <?php foreach ($tovars as $tovar): ?>
            <?php
            $image = $tovar->getImage();
            $nameTovar = $tovar->name;
            $price = floor(($tovar->price) / 100) . ' руб.';
            ?>
            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 col-12" data-toggle="tooltip" data-html="true" title='<?= $nameTovar ?>'>
                <a href="<?= Url::to(['/tovar/views', 'id' => $tovar->id]) ?>">
                    <img src="/web/<?= $image->getPath('500x500') ?>" alt="" class="img-fluid">
                </a>
                <div class="title-tov-gall">
                    <a href="<?= Url::to(['/tovar/views', 'id' => $tovar->id]) ?>">
                    <h4 class="light-text text-center"><?= $nameTovar ?></h4>
                    </a>
                </div>
                <div class="price-front">
                    <h4 class="light-text text-center text-danger"><?= $price ?></h4>
                </div>
                <div class="add-cart-front text-center">
                    <a href="<?= Url::to(['cart/add', 'id'=>$tovar->id]) ?>" data-id="<?= $tovar->id ?>" class="add-too-cart btn btn-large btn-outline-success"><i class="fas fa-cart-plus"></i> Добавить в корзину</a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<div class="moto-widget moto-widget-container moto-background-fixed moto-container_content_576d463d" data-widget="container" data-container="container" data-css-name="moto-container_content_576d463d">
    <div class="moto-widget moto-widget-container moto-container_content_5773d0ab" data-widget="container" data-container="container" data-css-name="moto-container_content_5773d0ab">
        <div class="moto-widget moto-widget-row row-fixed" data-widget="row">
            <div class="container-fluid">
                <div class="row">
                    <div class="moto-cell col-sm-2" data-container="container"></div>
                    <div class="moto-cell col-sm-8" data-container="container">
                        <div class="moto-widget moto-widget-spacer moto-preset-default moto-spacing-top-large moto-spacing-right-auto moto-spacing-bottom-medium moto-spacing-left-auto" data-widget="spacer" data-preset="default" data-spacing="lama">
                            <div class="moto-widget-spacer-block" style="height: 0px;"></div>
                        </div>
                        <div class="moto-widget moto-widget-spacer moto-preset-default moto-spacing-top-medium moto-spacing-right-auto moto-spacing-bottom-auto moto-spacing-left-auto" data-widget="spacer" data-preset="default" data-spacing="maaa">
                            <div class="moto-widget-spacer-block" style="height: 5px;"></div>
                        </div>
                        <div class="moto-widget moto-widget-text moto-preset-default moto-spacing-top-medium moto-spacing-right-auto moto-spacing-bottom-small moto-spacing-left-auto" data-widget="text" data-preset="default" data-spacing="masa">
                            <?= $setting->front_text_block ?>
                        </div>
                        <div class="moto-widget moto-widget-spacer moto-preset-default moto-spacing-top-medium moto-spacing-right-auto moto-spacing-bottom-small moto-spacing-left-auto" data-widget="spacer" data-preset="default" data-spacing="masa">
                            <div class="moto-widget-spacer-block" style="height: 0px;"></div>
                        </div>
                        <div class="moto-widget moto-widget-spacer moto-preset-default moto-spacing-top-large moto-spacing-right-auto moto-spacing-bottom-medium moto-spacing-left-auto" data-widget="spacer" data-preset="default" data-spacing="lama">
                            <div class="moto-widget-spacer-block" style="height: 0px;"></div>
                        </div>
                    </div>
                    <div class="moto-cell col-sm-2" data-container="container"></div>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/search.php
<?php

use yii\helpers\Url;
use yii\helpers\StringHelper;
use yii\widgets\LinkPager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$this->title = 'Поиск по слову ' . $q;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container">
    <h1 class="light-text text-center"><?= $this->title ?></h1>
    <div class="row">
        <?php foreach ($modelTovar as $tovar): ?>
            <?php
            $image = $tovar->getImage();
            $nameTovar = $tovar->name;
            $price = floor(($tovar->price) / 100) . ' руб.';
            ?>
            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 col-12" data-toggle="tooltip" data-html="true" title='<?= $nameTovar ?>'>
                <a href="<?= Url::to(['/tovar/views', 'id' => $tovar->id]) ?>">
                    <img src="/web/<?= $image->getPath('500x500') ?>" alt="" class="img-fluid">
                </a>
                <div class="title-tov-gall">
                    <a href="<?= Url::to(['/tovar/views', 'id' => $tovar->id]) ?>">
                        <h4 class="light-text text-center"><?= $nameTovar ?></h4>
                    </a>
                </div>
                <div class="price-front">
                    <h4 class="light-text text-center text-danger"><?= $price ?></h4>
                </div>
                <div class="add-cart-front text-center">
                    <a href="<?= Url::to(['cart/add', 'id' => $tovar->id]) ?>" data-id="<?= $tovar->id ?>" class="add-too-cart btn btn-large btn-outline-success"><i class="fas fa-cart-plus"></i> Добавить в корзину</a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <?php foreach ($models as $article): ?>
            <div class="col-12">
                <div class="w-100">
                    <a href="<?= Url::to(['/article/view', 'id' => $article->id]) ?>" class="text-dark">
                        <h2 class=""><?= $article->name ?> </h2>
                    </a>
                </div>
                <div class="content">
                    <?= StringHelper::truncateWords(strip_tags($article->body, '<p>'), 300) ?>
                </div>
                <div class="content">
                    <span> <i class="far fa-user"></i> <?= $article->user->first_name ?> </span>
                    <span> <i class="far fa-eye-slash"></i> <?= $article->count ?></span>
                    <span><a href="<?= Url::to(['/article/view', 'id' => $article->id]) ?>" class="readmore"><b>Подробнее</b> <i class="far fa-play-circle"></i> </a></span>
                </div>
                <hr>
            </div>

        <?php endforeach; ?>
    </div>
    <div class="row">
        <?php
        echo LinkPager::widget([
            'pagination' => $pages,
        ]);
        ?>
    </div>
</div>