models/Cart.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cart".
 *
 * @property int $id
 */
class Cart extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'cart';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
        ];
    }

    public function addToCart($tovar, $qty = 1) {
        if (isset($_SESSION['cart'][$tovar->id])) {
            $_SESSION['cart'][$tovar->id]['qty'] += $qty;
        } else {
            $_SESSION['cart'][$tovar->id] = [
                'qty' => $qty,
                'name' => $tovar->name,
                'price' => $tovar->price,
                'image' => $tovar->getImage()->getPath('500x500'),
            ];
        }
        $_SESSION['cart.qty'] = isset($_SESSION['cart.qty']) ? $_SESSION['cart.qty'] + $qty : $qty;
        $_SESSION['cart.sum'] = isset($_SESSION['cart.sum']) ? $_SESSION['cart.sum'] + $qty * $tovar->price : $qty * $tovar->price;
    }

    public function recalc($id) {
        if (!isset($_SESSION['cart'][$id])) return false;
        $qtyMinus = $_SESSION['cart'][$id]['qty'];
        $sumMinus = $_SESSION['cart'][$id]['price'] * $_SESSION['cart'][$id]['qty'];
        
        $_SESSION['cart.qty'] -= $qtyMinus;
        $_SESSION['cart.sum'] -= $sumMinus;
        unset($_SESSION['cart'][$id]);
    }

}

controllers/CartController.php
<?php

namespace app\controllers;

use app\models\Tovar;
use app\models\Cart;
use Yii;

class CartController extends \yii\web\Controller {

    public function actionAdd($id) {
        $this->layout = FALSE;
        $tovar = Tovar::findOne($id);
        if (empty($tovar)) {
            return false;
        }


        return $this->render('add', [
            'id' => $id,
            'tovar' => $tovar,
        ]);
    }
    
    public function actionAddnumb() {
        $id = Yii::$app->request->get('id');
        $numb = Yii::$app->request->get('numb');
        $this->layout = FALSE;
        $tovar = Tovar::findOne($id);
        if (empty($tovar)) {
            return false;
        }


        return $this->render('addnumb', [
            'id' => $id,
            'tovar' => $tovar,
            'numb' => $numb,
        ]);
    }

    public function actionView() {
        return $this->render('view');
    }
    
    public function actionNumb() {
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('numb', compact('session'));
    }
    public function actionShow() {
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('show', compact('session'));
    }
    
    
    public function actionClear() {
        return $this->render('clear');
    }
    
    public function actionDelitem($id) {
        return $this->render('delitem', [
            'id' => $id,
        ]);
    }

}

views/cart/add.php
<?php

use app\models\Cart;


$session = Yii::$app->session;
$session->open();

$cart = new Cart();

$cart->addToCart($tovar);

/* debug($session['cart']);
debug($session['cart.qty']);
debug($session['cart.sum']); */

views/cart/addnumb.php
<?php

use app\models\Cart;


$session = Yii::$app->session;
$session->open();

$cart = new Cart();

$cart->addToCart($tovar, $numb);

/* debug($session['cart']);
debug($session['cart.qty']);
debug($session['cart.sum']); */

views/cart/clear.php
<?php

$session = Yii::$app->session;
$session->open();
$session->remove('cart');
$session->remove('cart.qty');
$session->remove('cart.sum');

views/cart/delitem.php
<?php

$session = Yii::$app->session;
$session->open();

$cart = new app\models\Cart();
$cart->recalc($id);

views/cart/numb.php
<?php
use yii\helpers\Url;
?>
<?php if (!empty($session['cart'])): ?>
<a class=" nav-link text-success" href="<?= Url::to('/cart/view') ?>"><i class="fas fa-shopping-cart fa-2x"></i> (<?= $session['cart.qty'] ?>)</li></a>
<?php else: ?>
<a class="nav-link text-success"><i class="fas fa-shopping-cart fa-2x"></i> <li class="show-cart-numb"></li></a>
<?php endif; ?>

views/cart/show.php
<?php if (!empty($session['cart'])): ?>
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th scope="col">Фото</th>
                    <th scope="col">Название</th>
                    <th scope="col">Цена</th>
                    <th scope="col">Количество</th>
                    <th scope="col"><i class="far fa-trash-alt danger del-item-all" onclick="clearCard()"></i></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($session['cart'] as $id => $value): ?>
                    <tr>
                        <td><img src="/web/<?= $value['image'] ?>" width="150px" alt="" class="img-fluid"></td>
                        <td><?= $value['name'] ?></td>
                        <td><?= floor($value['price'] / 100) . ' руб. ' . ($value['price'] - ((floor($value['price'] / 100)) * 100)) . ' коп.' ?></td>
                        <td><?= $value['qty'] ?></td>
                        <td><i class="far fa-trash-alt danger del-item" data-id="<?= $id ?>" onclick="delItem(<?= $id ?>)"></i></td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td colspan="4">Итого: </td>
                    <td><?= $session['cart.qty'] ?></td>
                </tr>
                <tr>
                    <td colspan="4">На сумму: </td>
                    <td><?= floor($session['cart.sum'] / 100) . ' руб. ' . ($session['cart.sum'] - ((floor($session['cart.sum'] / 100)) * 100)) . ' коп.' ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="float-right">
    </div>
<?php else: ?>
    <h3>Корзина пуста</h3>

<?php endif; ?>

views/cart/view.php
<?php
$this->title = 'Корзина';

?>

<div class="container">
    <h2 class="light-text text-center"><?= $this->title ?></h2>
    <div class="show-card-tabl">
        
    </div>
    <div class="float-right">
        <a href="<?= yii\helpers\Url::to('/order') ?>" class="btn btn-success">Оформить заказ</a>
        <button type="button" class="btn btn-danger" onclick="clearCard()">Очистить корзину</button>
    </div>
</div>